//! Python classes for Data API v2 rows, registered on the `polyoxide.v2`
//! submodule. Each wraps the serialized Rust value, as the v1 classes do, so a
//! getter returns exactly what the typed row held. Nested objects (approval
//! contracts, combo legs, PnL points, freshness details) come back as dicts.
//!
//! Generated by `polyoxide-py/scripts/gen_v2_bindings.py rows`, then owned by
//! hand.

use pyo3::types::PyModuleMethods;

py_type!(
    PyV2Approvals,
    "Approvals",
    polyoxide_data::v2::types::Approvals,
    address,
    chain_id,
    checked_at,
    contracts,
);

py_type!(
    PyV2Position,
    "Position",
    polyoxide_data::v2::types::Position,
    archived,
    avg_price,
    condition_id,
    current_price,
    current_size,
    current_value,
    end_date,
    entry_cost_usdc,
    entry_fees_usdc,
    event_id,
    event_slug,
    icon,
    last_event_at,
    mergeable,
    name,
    negative_risk,
    opposite_outcome,
    opposite_token_id,
    outcome,
    outcome_index,
    percent_pnl,
    percent_realized_pnl,
    profile_image,
    proxy_wallet,
    realized_pnl,
    redeemable,
    slug,
    status,
    title,
    token_id,
    total_cost_usdc,
    total_pnl,
    total_size,
    unrealized_pnl,
    verified,
);

py_type!(
    PyV2ComboPosition,
    "ComboPosition",
    polyoxide_data::v2::types::ComboPosition,
    combo_condition_id,
    combo_position_id,
    current_size,
    entry_avg_price_usdc,
    entry_cost_usdc,
    entry_fees_usdc,
    first_entry_at,
    first_entry_at_micros,
    gross_entry_cost_usdc,
    legs,
    legs_pending,
    legs_resolved,
    legs_total,
    outcome_index,
    outcome_label,
    proxy_wallet,
    realized_payout_usdc,
    redeemable,
    resolved_at,
    status,
    updated_at,
    updated_at_micros,
);

py_type!(
    PyV2UserPnlSeries,
    "UserPnlSeries",
    polyoxide_data::v2::types::UserPnlSeries,
    fidelity,
    interval,
    points,
    proxy_wallet,
    source_fidelity,
);

py_type!(
    PyV2UserStats,
    "UserStats",
    polyoxide_data::v2::types::UserStats,
    all_time_pnl,
    biggest_win,
    join_date,
    proxy_wallet,
    trades,
    views,
);

py_type!(
    PyV2UserVolume,
    "UserVolume",
    polyoxide_data::v2::types::UserVolume,
    trade_count,
    volume,
    volume_usdc,
);

py_type!(
    PyV2PortfolioValue,
    "PortfolioValue",
    polyoxide_data::v2::types::PortfolioValue,
    proxy_wallet,
    value,
);

py_type!(
    PyV2Activity,
    "Activity",
    polyoxide_data::v2::types::Activity,
    bio,
    condition_id,
    event_slug,
    icon,
    is_combo,
    name,
    outcome,
    outcome_index,
    price,
    profile_image,
    profile_image_optimized,
    proxy_wallet,
    pseudonym,
    side,
    size,
    slug,
    timestamp,
    title,
    token_id,
    transaction_hash,
    activity_type => "type",
    usdc_size,
);

py_type!(
    PyV2ComboActivity,
    "ComboActivity",
    polyoxide_data::v2::types::ComboActivity,
    amount_usdc,
    block_number,
    combo_condition_id,
    combo_position_id,
    id,
    legs,
    payout_usdc,
    proxy_wallet,
    timestamp,
    transaction_hash,
    combo_activity_type => "type",
);

py_type!(
    PyV2Trade,
    "Trade",
    polyoxide_data::v2::types::Trade,
    bio,
    condition_id,
    event_slug,
    icon,
    name,
    outcome,
    outcome_index,
    price,
    profile_image,
    profile_image_optimized,
    proxy_wallet,
    pseudonym,
    side,
    size,
    slug,
    timestamp,
    title,
    token_id,
    transaction_hash,
);

py_type!(
    PyV2MetaHolder,
    "MetaHolder",
    polyoxide_data::v2::types::MetaHolder,
    holders,
    token_id,
);

py_type!(
    PyV2LiveVolume,
    "LiveVolume",
    polyoxide_data::v2::types::LiveVolume,
    conditions,
    taker_volume_total,
);

py_type!(
    PyV2OpenInterest,
    "OpenInterest",
    polyoxide_data::v2::types::OpenInterest,
    condition_id,
    value,
);

py_type!(
    PyV2PricePoint,
    "PricePoint",
    polyoxide_data::v2::types::PricePoint,
    price,
    resolution_seconds,
    timestamp,
);

py_type!(
    PyV2Resolution,
    "Resolution",
    polyoxide_data::v2::types::Resolution,
    condition_id,
    extended_review,
    last_update_timestamp,
    log_index,
    market_type,
    new_version_q,
    payouts,
    price,
    proposed_price,
    question_id,
    reporter,
    reproposed_price,
    resolution_source,
    resolved_at,
    resolved_block,
    status,
    transaction_hash,
    was_arbitrated,
    was_disputed,
);

py_type!(
    PyV2BiggestWinner,
    "BiggestWinner",
    polyoxide_data::v2::types::BiggestWinner,
    condition_id,
    event_id,
    event_slug,
    event_title,
    final_value,
    initial_value,
    kind,
    pnl,
    position_id,
    profile_image,
    resolved_at,
    user_id,
    user_name,
    win_rank,
);

py_type!(
    PyV2BuilderStanding,
    "BuilderStanding",
    polyoxide_data::v2::types::BuilderStanding,
    active_users,
    builder_code,
    builder_name,
    profile_image,
    rank,
    verified,
    volume,
);

py_type!(
    PyV2BuilderVolumePoint,
    "BuilderVolumePoint",
    polyoxide_data::v2::types::BuilderVolumePoint,
    active_users,
    builder_code,
    builder_name,
    date,
    profile_image,
    rank,
    verified,
    volume,
);

py_type!(
    PyV2LeaderboardEntry,
    "LeaderboardEntry",
    polyoxide_data::v2::types::LeaderboardEntry,
    pnl,
    profile_image,
    rank,
    user_id,
    user_name,
    verified,
    volume,
    x_username,
);

py_type!(
    PyV2LeaderboardUserEntry,
    "LeaderboardUserEntry",
    polyoxide_data::v2::types::LeaderboardUserEntry,
    pnl,
    profile_image,
    rank_pnl,
    rank_volume,
    user_id,
    user_name,
    verified,
    volume,
    x_username,
);

py_type!(
    PyV2ServiceStatus,
    "ServiceStatus",
    polyoxide_data::v2::types::ServiceStatus,
    age_seconds,
    computed_at,
    ingestion,
    serving,
);

py_type!(
    PyV2Pagination,
    "Pagination",
    polyoxide_data::v2::Pagination,
    has_more,
    limit,
    next_cursor,
    offset,
);

pub fn register(m: &pyo3::Bound<'_, pyo3::types::PyModule>) -> pyo3::PyResult<()> {
    m.add_class::<PyV2Approvals>()?;
    m.add_class::<PyV2Position>()?;
    m.add_class::<PyV2ComboPosition>()?;
    m.add_class::<PyV2UserPnlSeries>()?;
    m.add_class::<PyV2UserStats>()?;
    m.add_class::<PyV2UserVolume>()?;
    m.add_class::<PyV2PortfolioValue>()?;
    m.add_class::<PyV2Activity>()?;
    m.add_class::<PyV2ComboActivity>()?;
    m.add_class::<PyV2Trade>()?;
    m.add_class::<PyV2MetaHolder>()?;
    m.add_class::<PyV2LiveVolume>()?;
    m.add_class::<PyV2OpenInterest>()?;
    m.add_class::<PyV2PricePoint>()?;
    m.add_class::<PyV2Resolution>()?;
    m.add_class::<PyV2BiggestWinner>()?;
    m.add_class::<PyV2BuilderStanding>()?;
    m.add_class::<PyV2BuilderVolumePoint>()?;
    m.add_class::<PyV2LeaderboardEntry>()?;
    m.add_class::<PyV2LeaderboardUserEntry>()?;
    m.add_class::<PyV2ServiceStatus>()?;
    m.add_class::<PyV2Pagination>()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    //! `test_stub_consistency.py` compares attribute *names* with the stub, and
    //! a getter that looks up the wrong key still has the right name: `get_field`
    //! returns `None` for a key that is not there. So for every class this checks
    //! two things against the captured payloads in
    //! `polyoxide-data/tests/fixtures/v2/`:
    //!
    //! 1. its getters are exactly the keys of each captured row, decoded into the
    //!    Rust type and serialized back, so no field is missing or invented;
    //! 2. each getter reads its own key. The class is built over a row whose
    //!    every value is its own key name, so a field that is `null` in every
    //!    capture cannot hide a wrong key.

    use std::collections::BTreeSet;

    use polyoxide_data::v2::{self, types::*};
    use pyo3::{prelude::*, types::PyDict, PyClass, PyClassInitializer};
    use serde::{de::DeserializeOwned, Serialize};
    use serde_json::{Map, Value};

    use super::*;

    /// The objects at `pointer` in a captured body: the row itself, or each
    /// element of a list.
    fn captured(fixture: &str, pointer: &str) -> Vec<Value> {
        let path = format!(
            "{}/../polyoxide-data/tests/fixtures/v2/{fixture}.json",
            env!("CARGO_MANIFEST_DIR")
        );
        let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
        let body: Value = serde_json::from_str(&text).expect("fixture is JSON");
        match body.pointer(pointer) {
            Some(Value::Array(rows)) => rows.clone(),
            Some(row @ Value::Object(_)) => vec![row.clone()],
            other => panic!("{fixture}.json has no rows at {pointer}: {other:?}"),
        }
    }

    fn getters<W: PyClass>(py: Python<'_>) -> BTreeSet<String> {
        let locals = PyDict::new(py);
        locals.set_item("cls", py.get_type::<W>()).unwrap();
        py.run(
            c"names = {k for k, v in vars(cls).items() if type(v).__name__ == 'getset_descriptor'}",
            None,
            Some(&locals),
        )
        .unwrap();
        locals
            .get_item("names")
            .unwrap()
            .unwrap()
            .extract()
            .unwrap()
    }

    fn check<T, W>(py: Python<'_>, rows: Vec<Value>, raw: fn(Value) -> W, renames: &[(&str, &str)])
    where
        T: DeserializeOwned + Serialize,
        W: PyClass + Into<PyClassInitializer<W>>,
    {
        let class = std::any::type_name::<T>();
        let key = |getter: &str| {
            renames
                .iter()
                .find(|(field, _)| *field == getter)
                .map_or(getter, |(_, key)| *key)
                .to_owned()
        };
        let getters = getters::<W>(py);
        let covered: BTreeSet<String> = getters.iter().map(|g| key(g)).collect();

        assert!(!rows.is_empty(), "{class}: no captured rows");
        for row in rows {
            let typed: T = serde_json::from_value(row).unwrap_or_else(|e| panic!("{class}: {e}"));
            let Value::Object(fields) = serde_json::to_value(&typed).unwrap() else {
                panic!("{class} does not serialize to an object");
            };
            let keys: BTreeSet<String> = fields.keys().cloned().collect();
            assert_eq!(covered, keys, "{class}: getters differ from the row's keys");
        }

        let marked: Map<String, Value> = covered
            .iter()
            .map(|key| (key.clone(), Value::String(key.clone())))
            .collect();
        let obj = Bound::new(py, raw(Value::Object(marked)))
            .unwrap()
            .into_any();
        for getter in &getters {
            let read: Option<String> = obj.getattr(getter.as_str()).unwrap().extract().unwrap();
            assert_eq!(
                read.as_deref(),
                Some(key(getter).as_str()),
                "{class}.{getter} does not read the {:?} key",
                key(getter)
            );
        }
    }

    #[test]
    fn every_v2_getter_reads_its_own_key() {
        Python::attach(|py| {
            macro_rules! check {
                ($row:ty, $class:ident, [$($fixture:literal),+] $(, $field:literal => $key:literal)?) => {
                    check::<$row, $class>(
                        py,
                        [$($fixture),+].iter().flat_map(|f| captured(f, "/data")).collect(),
                        |inner| $class { inner },
                        &[$(($field, $key))?],
                    )
                };
            }

            check!(Approvals, PyV2Approvals, ["approvals"]);
            check!(Position, PyV2Position, ["positions", "positions_closed"]);
            check!(ComboPosition, PyV2ComboPosition, ["combo_positions"]);
            check!(UserPnlSeries, PyV2UserPnlSeries, ["user_pnl"]);
            check!(UserStats, PyV2UserStats, ["user_stats"]);
            check!(UserVolume, PyV2UserVolume, ["user_volume"]);
            check!(PortfolioValue, PyV2PortfolioValue, ["value"]);
            check!(Activity, PyV2Activity, ["activity", "activity_tips"], "activity_type" => "type");
            check!(ComboActivity, PyV2ComboActivity, ["combo_activity"], "combo_activity_type" => "type");
            check!(Trade, PyV2Trade, ["trades"]);
            check!(MetaHolder, PyV2MetaHolder, ["holders", "holders_pnl"]);
            check!(LiveVolume, PyV2LiveVolume, ["live_volume"]);
            check!(
                OpenInterest,
                PyV2OpenInterest,
                ["open_interest", "open_interest_global"]
            );
            check!(PricePoint, PyV2PricePoint, ["prices_history"]);
            check!(Resolution, PyV2Resolution, ["resolutions"]);
            check!(
                BiggestWinner,
                PyV2BiggestWinner,
                ["biggest_winners", "biggest_winners_combos"]
            );
            check!(
                BuilderStanding,
                PyV2BuilderStanding,
                ["builders_leaderboard"]
            );
            check!(
                BuilderVolumePoint,
                PyV2BuilderVolumePoint,
                ["builder_volume"]
            );
            check!(LeaderboardEntry, PyV2LeaderboardEntry, ["leaderboard"]);
            check!(
                LeaderboardUserEntry,
                PyV2LeaderboardUserEntry,
                ["leaderboard_user"]
            );
            check!(ServiceStatus, PyV2ServiceStatus, ["status"]);

            let paged = [
                "activity",
                "biggest_winners",
                "builders_leaderboard",
                "combo_activity",
                "combo_positions",
                "holders",
                "leaderboard",
                "positions",
                "prices_history",
                "trades",
            ];
            let pagination = paged
                .iter()
                .flat_map(|f| captured(f, "/pagination"))
                .collect();
            check::<v2::Pagination, PyV2Pagination>(
                py,
                pagination,
                |inner| PyV2Pagination { inner },
                &[],
            );
        });
    }
}
