"""Guard: the ``__init__.pyi`` type stub must match the compiled extension.

The Python classes are generated by the ``py_type!`` macro
(``polyoxide-py/src/macros.rs``). That macro emits a getter named after the
*snake_case Rust field identifier*; the ``field => "jsonKey"`` form only changes
the serde lookup key, **not** the Python attribute name. The hand-maintained
``__init__.pyi`` stub has historically drifted from this — declaring properties
under the JSON key (e.g. ``questionID``, ``volume24hr``, ``proxyWallet``,
``t``/``p``, ``type``) that do not exist on the compiled classes, so type
checkers pass code that fails at runtime with ``AttributeError``.

This test introspects the *compiled* module (the real source of truth, whatever
produced each getter) and asserts the stub declares exactly the public
attributes each class actually exposes — no missing entries, no phantom ones.
It hits no network (it only inspects class objects, never constructs clients).
"""

from __future__ import annotations

import ast
import pathlib

import pytest

import polyoxide
from polyoxide import _polyoxide

# Stub lives next to the package source, two levels up from this test file:
#   polyoxide-py/tests/test_stub_consistency.py
#   polyoxide-py/python/polyoxide/__init__.pyi
_STUB_PATH = (
    pathlib.Path(__file__).resolve().parents[1] / "python" / "polyoxide" / "__init__.pyi"
)

# pyo3 maps Rust error types onto Python ``Exception`` subclasses, which inherit
# ``args``/``add_note``/``with_traceback`` from ``BaseException``. A ``.pyi`` may
# legitimately omit inherited members, so they are not drift.
_INHERITED_EXCEPTION_MEMBERS = {n for n in dir(Exception) if not n.startswith("_")}


def _public_members(names: object) -> set[str]:
    """Public (non-dunder) attribute names, minus inherited exception noise."""
    return {n for n in dir(names) if not n.startswith("_")} - _INHERITED_EXCEPTION_MEMBERS


def _stub_classes() -> dict[str, set[str]]:
    """Map each class declared in the stub to its public member names."""
    tree = ast.parse(_STUB_PATH.read_text())
    classes: dict[str, set[str]] = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes[node.name] = {
                member.name
                for member in node.body
                if isinstance(member, ast.FunctionDef) and not member.name.startswith("_")
            }
    return classes


def _resolve(name: str) -> type | None:
    """Find the compiled class for a stub class name, if it is module-level."""
    return getattr(polyoxide, name, None) or getattr(_polyoxide, name, None)


_STUB_CLASSES = _stub_classes()


def test_stub_declares_classes() -> None:
    """Sanity check that the stub was parsed and is non-trivial."""
    assert len(_STUB_CLASSES) > 50, "expected the stub to declare many classes"


@pytest.mark.parametrize("class_name", sorted(_STUB_CLASSES))
def test_stub_matches_compiled_class(class_name: str) -> None:
    """Every stub class's members must equal the compiled class's members."""
    real_cls = _resolve(class_name)
    assert real_cls is not None, (
        f"stub declares class '{class_name}' that is not exported by the "
        f"compiled module (polyoxide / polyoxide._polyoxide)"
    )

    stub_members = _STUB_CLASSES[class_name]
    real_members = _public_members(real_cls)

    phantom = sorted(stub_members - real_members)
    missing = sorted(real_members - stub_members)

    detail = []
    if phantom:
        detail.append(
            f"declared in stub but absent on the class (will raise "
            f"AttributeError at runtime): {phantom}"
        )
    if missing:
        detail.append(f"exposed by the class but missing from the stub: {missing}")

    assert not detail, (
        f"`{class_name}` type stub is out of sync with the compiled API. "
        + "; ".join(detail)
        + ". Update polyoxide-py/python/polyoxide/__init__.pyi to match the "
        "snake_case getters emitted by the py_type! macro."
    )
