"""Guard: the ``__init__.pyi`` type stub must match the compiled extension.

The Python classes are generated by the ``py_type!`` macro
(``polyoxide-py/src/macros.rs``). That macro emits a getter named after the
*snake_case Rust field identifier*; the ``field => "jsonKey"`` form only changes
the serde lookup key, **not** the Python attribute name. The hand-maintained
``__init__.pyi`` stub has historically drifted from this — declaring properties
under the JSON key (e.g. ``questionID``, ``volume24hr``, ``proxyWallet``,
``t``/``p``, ``type``) that do not exist on the compiled classes, so type
checkers pass code that fails at runtime with ``AttributeError``.

This test introspects the *compiled* module (the real source of truth, whatever
produced each getter) and asserts the stub declares exactly the public
attributes each class actually exposes — no missing entries, no phantom ones.
It hits no network (it only inspects class objects, never constructs clients).
"""

from __future__ import annotations

import ast
import inspect
import pathlib

import pytest

import polyoxide
from polyoxide import _polyoxide

# Stub lives next to the package source, two levels up from this test file:
#   polyoxide-py/tests/test_stub_consistency.py
#   polyoxide-py/python/polyoxide/__init__.pyi
_STUB_PATH = (
    pathlib.Path(__file__).resolve().parents[1] / "python" / "polyoxide" / "__init__.pyi"
)

# pyo3 maps Rust error types onto Python ``Exception`` subclasses, which inherit
# ``args``/``add_note``/``with_traceback`` from ``BaseException``. A ``.pyi`` may
# legitimately omit inherited members, so they are not drift.
_INHERITED_EXCEPTION_MEMBERS = {n for n in dir(Exception) if not n.startswith("_")}


def _public_members(names: object) -> set[str]:
    """Public (non-dunder) attribute names, minus inherited exception noise."""
    return {n for n in dir(names) if not n.startswith("_")} - _INHERITED_EXCEPTION_MEMBERS


def _stub_classes() -> dict[str, set[str]]:
    """Map each class declared in the stub to its public member names."""
    tree = ast.parse(_STUB_PATH.read_text())
    classes: dict[str, set[str]] = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            classes[node.name] = {
                member.name
                for member in node.body
                if isinstance(member, ast.FunctionDef) and not member.name.startswith("_")
            }
    return classes


def _resolve(name: str) -> type | None:
    """Find the compiled class for a stub class name, if it is module-level."""
    return getattr(polyoxide, name, None) or getattr(_polyoxide, name, None)


_STUB_CLASSES = _stub_classes()


def test_stub_declares_classes() -> None:
    """Sanity check that the stub was parsed and is non-trivial."""
    assert len(_STUB_CLASSES) > 50, "expected the stub to declare many classes"


@pytest.mark.parametrize("class_name", sorted(_STUB_CLASSES))
def test_stub_matches_compiled_class(class_name: str) -> None:
    """Every stub class's members must equal the compiled class's members."""
    real_cls = _resolve(class_name)
    assert real_cls is not None, (
        f"stub declares class '{class_name}' that is not exported by the "
        f"compiled module (polyoxide / polyoxide._polyoxide)"
    )

    stub_members = _STUB_CLASSES[class_name]
    real_members = _public_members(real_cls)

    phantom = sorted(stub_members - real_members)
    missing = sorted(real_members - stub_members)

    detail = []
    if phantom:
        detail.append(
            f"declared in stub but absent on the class (will raise "
            f"AttributeError at runtime): {phantom}"
        )
    if missing:
        detail.append(f"exposed by the class but missing from the stub: {missing}")

    assert not detail, (
        f"`{class_name}` type stub is out of sync with the compiled API. "
        + "; ".join(detail)
        + ". Update polyoxide-py/python/polyoxide/__init__.pyi to match the "
        "snake_case getters emitted by the py_type! macro."
    )


# ── polyoxide.v2 ──────────────────────────────────────────────────────────────
#
# The v2 classes reuse v1 names (`Trade`, `Position`, ...), so they have their
# own stub and resolve on `polyoxide.v2` only: falling back to the top-level
# module would compare a v2 stub with the v1 class of the same name.

_V2_STUB_PATH = _STUB_PATH.with_name("v2.pyi")
_V2_STUB = {
    node.name: node
    for node in ast.parse(_V2_STUB_PATH.read_text()).body
    if isinstance(node, ast.ClassDef)
}


def _v2_methods(class_name: str) -> list[ast.FunctionDef]:
    """Public stub methods of a v2 class, without its properties."""
    return [
        member
        for member in _V2_STUB[class_name].body
        if isinstance(member, ast.FunctionDef)
        and not member.name.startswith("_")
        and not any(getattr(d, "id", None) == "property" for d in member.decorator_list)
    ]


_V2_METHODS = sorted((c, m.name) for c in _V2_STUB for m in _v2_methods(c))


def test_v2_stub_declares_every_v2_export() -> None:
    assert set(_V2_STUB) == set(polyoxide.v2.__all__)


@pytest.mark.parametrize("class_name", sorted(_V2_STUB))
def test_v2_stub_matches_compiled_class(class_name: str) -> None:
    stub_members = {
        member.name
        for member in _V2_STUB[class_name].body
        if isinstance(member, ast.FunctionDef) and not member.name.startswith("_")
    }
    real_members = _public_members(getattr(polyoxide.v2, class_name))
    assert stub_members == real_members, (
        f"polyoxide/v2.pyi `{class_name}` is out of sync with the compiled class"
    )


def _stub_parameters(fn: ast.FunctionDef) -> list[tuple[str, str, bool]]:
    """(name, positional|keyword, has a default) for each parameter after self."""
    positional = fn.args.args[1:]
    first_default = len(positional) - len(fn.args.defaults)
    return [
        (arg.arg, "positional", i >= first_default) for i, arg in enumerate(positional)
    ] + [
        (arg.arg, "keyword", default is not None)
        for arg, default in zip(fn.args.kwonlyargs, fn.args.kw_defaults)
    ]


def _compiled_parameters(method: object) -> list[tuple[str, str, bool]]:
    kinds = {
        inspect.Parameter.POSITIONAL_OR_KEYWORD: "positional",
        inspect.Parameter.KEYWORD_ONLY: "keyword",
    }
    parameters = list(inspect.signature(method).parameters.values())[1:]
    return [(p.name, kinds[p.kind], p.default is not p.empty) for p in parameters]


@pytest.mark.parametrize(
    ("class_name", "method"), _V2_METHODS, ids=[f"{c}.{m}" for c, m in _V2_METHODS]
)
def test_v2_stub_signature_matches_compiled_method(class_name: str, method: str) -> None:
    """Parameter names, order, kinds and defaults, which member names alone miss.

    Only v2 is checked: its signatures all come from `#[pyo3(signature = ...)]`,
    so the compiled `__text_signature__` is exact.
    """
    stub = next(m for m in _v2_methods(class_name) if m.name == method)
    compiled = getattr(getattr(polyoxide.v2, class_name), method)
    assert _stub_parameters(stub) == _compiled_parameters(compiled)
