from __future__ import annotations

from collections.abc import Coroutine
from typing import Any

# =============================================================================
# Errors
# =============================================================================

class PolyoxideError(Exception):
    """Base exception for all polyoxide errors."""
    ...

class ApiError(PolyoxideError):
    """API returned an error response."""
    ...

class AuthenticationError(PolyoxideError):
    """Authentication credentials are invalid or missing."""
    ...

class ValidationError(PolyoxideError):
    """Request parameters failed validation."""
    ...

class RateLimitError(PolyoxideError):
    """API rate limit was exceeded."""
    ...

class NetworkError(PolyoxideError):
    """Network connectivity error."""
    ...

class TimeoutError(PolyoxideError):
    """Request timed out."""
    ...

# =============================================================================
# Gamma type classes
# =============================================================================

class Market:
    """A Polymarket prediction market."""
    @property
    def id(self) -> Any: ...
    @property
    def condition_id(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def question(self) -> Any: ...
    @property
    def description(self) -> Any: ...
    @property
    def category(self) -> Any: ...
    @property
    def active(self) -> Any: ...
    @property
    def closed(self) -> Any: ...
    @property
    def archived(self) -> Any: ...
    @property
    def question_id(self) -> Any: ...
    @property
    def tokens(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    @property
    def neg_risk(self) -> Any: ...
    @property
    def volume(self) -> Any: ...
    @property
    def liquidity(self) -> Any: ...
    @property
    def volume_num(self) -> Any: ...
    @property
    def liquidity_num(self) -> Any: ...
    @property
    def end_date_iso(self) -> Any: ...
    @property
    def start_date_iso(self) -> Any: ...
    @property
    def volume_24hr(self) -> Any: ...
    @property
    def volume_1wk(self) -> Any: ...
    @property
    def volume_1mo(self) -> Any: ...
    @property
    def volume_1yr(self) -> Any: ...
    @property
    def submitted_by(self) -> Any: ...
    @property
    def denomination_token(self) -> Any: ...
    @property
    def image(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def outcomes(self) -> Any: ...
    @property
    def outcome_prices(self) -> Any: ...
    @property
    def last_trade_price(self) -> Any: ...
    @property
    def best_bid(self) -> Any: ...
    @property
    def best_ask(self) -> Any: ...
    @property
    def spread(self) -> Any: ...
    @property
    def one_day_price_change(self) -> Any: ...
    @property
    def one_week_price_change(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def updated_at(self) -> Any: ...
    @property
    def closed_time(self) -> Any: ...
    @property
    def market_maker_address(self) -> Any: ...
    @property
    def clob_token_ids(self) -> Any: ...
    @property
    def enable_order_book(self) -> Any: ...
    @property
    def accepting_orders(self) -> Any: ...
    @property
    def comment_count(self) -> Any: ...
    @property
    def featured(self) -> Any: ...
    @property
    def restricted(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MarketToken:
    """A token within a prediction market."""
    @property
    def token_id(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def price(self) -> Any: ...
    @property
    def winner(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Event:
    """A Polymarket event grouping related markets."""
    @property
    def id(self) -> Any: ...
    @property
    def ticker(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def subtitle(self) -> Any: ...
    @property
    def description(self) -> Any: ...
    @property
    def start_date(self) -> Any: ...
    @property
    def end_date(self) -> Any: ...
    @property
    def image(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def active(self) -> Any: ...
    @property
    def closed(self) -> Any: ...
    @property
    def archived(self) -> Any: ...
    @property
    def featured(self) -> Any: ...
    @property
    def restricted(self) -> Any: ...
    @property
    def liquidity(self) -> Any: ...
    @property
    def open_interest(self) -> Any: ...
    @property
    def volume_24hr(self) -> Any: ...
    @property
    def volume_1wk(self) -> Any: ...
    @property
    def volume_1mo(self) -> Any: ...
    @property
    def markets(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    @property
    def series(self) -> Any: ...
    @property
    def neg_risk(self) -> Any: ...
    @property
    def neg_risk_market_id(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def updated_at(self) -> Any: ...
    @property
    def category(self) -> Any: ...
    @property
    def comments_enabled(self) -> Any: ...
    @property
    def competitive(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SeriesInfo:
    """Summary information about a market series."""
    @property
    def id(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def ticker(self) -> Any: ...
    @property
    def series_type(self) -> Any: ...
    @property
    def recurrence(self) -> Any: ...
    @property
    def image(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def active(self) -> Any: ...
    @property
    def closed(self) -> Any: ...
    @property
    def archived(self) -> Any: ...
    @property
    def volume_24hr(self) -> Any: ...
    @property
    def comment_count(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SeriesData:
    """Full data for a market series including events."""
    @property
    def id(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def description(self) -> Any: ...
    @property
    def image(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def active(self) -> Any: ...
    @property
    def closed(self) -> Any: ...
    @property
    def archived(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    @property
    def volume(self) -> Any: ...
    @property
    def liquidity(self) -> Any: ...
    @property
    def events(self) -> Any: ...
    @property
    def competitive(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Tag:
    """A tag used to categorize markets and events."""
    @property
    def id(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def label(self) -> Any: ...
    @property
    def force_show(self) -> Any: ...
    @property
    def force_hide(self) -> Any: ...
    @property
    def is_carousel(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def updated_at(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SportMetadata:
    """Metadata for a sport category."""
    @property
    def id(self) -> Any: ...
    @property
    def sport(self) -> Any: ...
    @property
    def image(self) -> Any: ...
    @property
    def resolution(self) -> Any: ...
    @property
    def ordering(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    @property
    def series(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Team:
    """A sports team."""
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def league(self) -> Any: ...
    @property
    def record(self) -> Any: ...
    @property
    def logo(self) -> Any: ...
    @property
    def abbreviation(self) -> Any: ...
    @property
    def alias(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def updated_at(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Comment:
    """A comment on a market, event, or series."""
    @property
    def id(self) -> Any: ...
    @property
    def body(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def updated_at(self) -> Any: ...
    @property
    def deleted_at(self) -> Any: ...
    @property
    def user(self) -> Any: ...
    @property
    def market_id(self) -> Any: ...
    @property
    def event_id(self) -> Any: ...
    @property
    def series_id(self) -> Any: ...
    @property
    def parent_id(self) -> Any: ...
    @property
    def reactions(self) -> Any: ...
    @property
    def positions(self) -> Any: ...
    @property
    def like_count(self) -> Any: ...
    @property
    def dislike_count(self) -> Any: ...
    @property
    def reply_count(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CommentUser:
    """A user who authored a comment."""
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def avatar(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CommentReaction:
    """A reaction on a comment."""
    @property
    def user_id(self) -> Any: ...
    @property
    def reaction_type(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CommentPosition:
    """A position held by a comment author."""
    @property
    def token_id(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def shares(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CountResponse:
    """A response containing a count value."""
    @property
    def count(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Cursor:
    """A pagination cursor."""
    @property
    def next_cursor(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SearchResponse:
    """Search results containing profiles, events, and tags."""
    @property
    def profiles(self) -> Any: ...
    @property
    def events(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SearchProfile:
    """A user profile returned from search."""
    @property
    def address(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def profile_image(self) -> Any: ...
    @property
    def pseudonym(self) -> Any: ...
    @property
    def bio(self) -> Any: ...
    @property
    def proxy_wallet(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UserResponse:
    """A Polymarket user profile response."""
    @property
    def proxy(self) -> Any: ...
    @property
    def address(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def created_at(self) -> Any: ...
    @property
    def profile_image(self) -> Any: ...
    @property
    def display_username_public(self) -> Any: ...
    @property
    def bio(self) -> Any: ...
    @property
    def pseudonym(self) -> Any: ...
    @property
    def x_username(self) -> Any: ...
    @property
    def verified_badge(self) -> Any: ...
    @property
    def users(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UserInfo:
    """User info with role flags."""
    @property
    def id(self) -> Any: ...
    @property
    def creator(self) -> Any: ...
    @property
    def moderator(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# =============================================================================
# CLOB type classes
# =============================================================================

class ClobMarket:
    """A CLOB order book market."""
    @property
    def condition_id(self) -> Any: ...
    @property
    def question_id(self) -> Any: ...
    @property
    def tokens(self) -> Any: ...
    @property
    def rewards(self) -> Any: ...
    @property
    def minimum_order_size(self) -> Any: ...
    @property
    def minimum_tick_size(self) -> Any: ...
    @property
    def description(self) -> Any: ...
    @property
    def category(self) -> Any: ...
    @property
    def end_date_iso(self) -> Any: ...
    @property
    def question(self) -> Any: ...
    @property
    def active(self) -> Any: ...
    @property
    def closed(self) -> Any: ...
    @property
    def archived(self) -> Any: ...
    @property
    def neg_risk(self) -> Any: ...
    @property
    def neg_risk_market_id(self) -> Any: ...
    @property
    def enable_order_book(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ClobMarketToken:
    """A token within a CLOB market."""
    @property
    def token_id(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def price(self) -> Any: ...
    @property
    def winner(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ListMarketsResponse:
    """Paginated list of CLOB markets."""
    @property
    def data(self) -> Any: ...
    @property
    def next_cursor(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OrderBook:
    """Order book for a market token."""
    @property
    def market(self) -> Any: ...
    @property
    def asset_id(self) -> Any: ...
    @property
    def bids(self) -> Any: ...
    @property
    def asks(self) -> Any: ...
    @property
    def timestamp(self) -> Any: ...
    @property
    def hash(self) -> Any: ...
    @property
    def min_order_size(self) -> Any: ...
    @property
    def tick_size(self) -> Any: ...
    @property
    def neg_risk(self) -> Any: ...
    @property
    def last_trade_price(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OrderLevel:
    """A price level in the order book."""
    @property
    def price(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PriceResponse:
    """A price response for a token."""
    @property
    def price(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MidpointResponse:
    """The midpoint price for a token."""
    @property
    def mid(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PriceHistoryPoint:
    """A single point in a price history series."""
    @property
    def timestamp(self) -> Any: ...
    @property
    def price(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PricesHistoryResponse:
    """Price history for a token."""
    @property
    def history(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class NegRiskResponse:
    """Whether a token uses negative risk."""
    @property
    def neg_risk(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class FeeRateResponse:
    """Fee rate for a token."""
    @property
    def base_fee(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TickSizeResponse:
    """Minimum tick size for a token."""
    @property
    def minimum_tick_size(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class SpreadResponse:
    """Bid-ask spread for a token."""
    @property
    def token_id(self) -> Any: ...
    @property
    def spread(self) -> Any: ...
    @property
    def bid(self) -> Any: ...
    @property
    def ask(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LastTradePriceResponse:
    """Last trade price for a token."""
    @property
    def token_id(self) -> Any: ...
    @property
    def last_trade_price(self) -> Any: ...
    @property
    def timestamp(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LiveActivityEvent:
    """A live activity event for a market."""
    @property
    def condition_id(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class CalculatePriceResponse:
    """Calculated price for a given amount."""
    @property
    def price(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ServerTimeResponse:
    """Server time from the CLOB API."""
    @property
    def time(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# =============================================================================
# Data type classes
# =============================================================================

class Position:
    """An open position held by a user."""
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def asset(self) -> Any: ...
    @property
    def condition_id(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def avg_price(self) -> Any: ...
    @property
    def initial_value(self) -> Any: ...
    @property
    def current_value(self) -> Any: ...
    @property
    def cash_pnl(self) -> Any: ...
    @property
    def percent_pnl(self) -> Any: ...
    @property
    def total_bought(self) -> Any: ...
    @property
    def realized_pnl(self) -> Any: ...
    @property
    def percent_realized_pnl(self) -> Any: ...
    @property
    def cur_price(self) -> Any: ...
    @property
    def redeemable(self) -> Any: ...
    @property
    def mergeable(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def event_slug(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def outcome_index(self) -> Any: ...
    @property
    def opposite_outcome(self) -> Any: ...
    @property
    def opposite_asset(self) -> Any: ...
    @property
    def end_date(self) -> Any: ...
    @property
    def negative_risk(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ClosedPosition:
    """A closed position for a user."""
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def asset(self) -> Any: ...
    @property
    def condition_id(self) -> Any: ...
    @property
    def avg_price(self) -> Any: ...
    @property
    def total_bought(self) -> Any: ...
    @property
    def realized_pnl(self) -> Any: ...
    @property
    def cur_price(self) -> Any: ...
    @property
    def timestamp(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def event_slug(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def outcome_index(self) -> Any: ...
    @property
    def opposite_outcome(self) -> Any: ...
    @property
    def opposite_asset(self) -> Any: ...
    @property
    def end_date(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Trade:
    """A trade executed on a market."""
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def side(self) -> Any: ...
    @property
    def asset(self) -> Any: ...
    @property
    def condition_id(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def price(self) -> Any: ...
    @property
    def timestamp(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def event_slug(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    @property
    def outcome_index(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def pseudonym(self) -> Any: ...
    @property
    def transaction_hash(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Activity:
    """An activity event for a user."""
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def timestamp(self) -> Any: ...
    @property
    def condition_id(self) -> Any: ...
    @property
    def activity_type(self) -> Any: ...
    @property
    def size(self) -> Any: ...
    @property
    def usdc_size(self) -> Any: ...
    @property
    def transaction_hash(self) -> Any: ...
    @property
    def price(self) -> Any: ...
    @property
    def asset(self) -> Any: ...
    @property
    def side(self) -> Any: ...
    @property
    def outcome_index(self) -> Any: ...
    @property
    def title(self) -> Any: ...
    @property
    def slug(self) -> Any: ...
    @property
    def icon(self) -> Any: ...
    @property
    def outcome(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UserValue:
    """A user's position value."""
    @property
    def user(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class OpenInterest:
    """Open interest for a market."""
    @property
    def market(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class UserTraded:
    """Whether a user has traded."""
    @property
    def user(self) -> Any: ...
    @property
    def traded(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MarketHolders:
    """Holders of a market token."""
    @property
    def token(self) -> Any: ...
    @property
    def holders(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Holder:
    """A holder of a market token."""
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def bio(self) -> Any: ...
    @property
    def asset(self) -> Any: ...
    @property
    def pseudonym(self) -> Any: ...
    @property
    def amount(self) -> Any: ...
    @property
    def display_username_public(self) -> Any: ...
    @property
    def outcome_index(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def profile_image(self) -> Any: ...
    @property
    def verified(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class TraderRanking:
    """A trader's ranking on the leaderboard."""
    @property
    def rank(self) -> Any: ...
    @property
    def proxy_wallet(self) -> Any: ...
    @property
    def user_name(self) -> Any: ...
    @property
    def vol(self) -> Any: ...
    @property
    def pnl(self) -> Any: ...
    @property
    def profile_image(self) -> Any: ...
    @property
    def x_username(self) -> Any: ...
    @property
    def verified_badge(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BuilderRanking:
    """A builder's ranking on the leaderboard."""
    @property
    def rank(self) -> Any: ...
    @property
    def builder(self) -> Any: ...
    @property
    def volume(self) -> Any: ...
    @property
    def active_users(self) -> Any: ...
    @property
    def verified(self) -> Any: ...
    @property
    def builder_logo(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class BuilderVolume:
    """A builder's volume data point."""
    @property
    def dt(self) -> Any: ...
    @property
    def builder(self) -> Any: ...
    @property
    def builder_logo(self) -> Any: ...
    @property
    def verified(self) -> Any: ...
    @property
    def volume(self) -> Any: ...
    @property
    def active_users(self) -> Any: ...
    @property
    def rank(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class LiveVolume:
    """Live trading volume data."""
    @property
    def total(self) -> Any: ...
    @property
    def markets(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MarketVolume:
    """Trading volume for a specific market."""
    @property
    def market(self) -> Any: ...
    @property
    def value(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class HealthResponse:
    """Health check response from the Data API."""
    @property
    def data(self) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# =============================================================================
# Gamma namespace classes
# =============================================================================

class GammaMarkets:
    """Async namespace for Gamma market endpoints."""
    def get(
        self, id: str, *, include_tag: bool | None = None
    ) -> Coroutine[Any, Any, Market]:
        """Get a market by ID."""
        ...
    def get_by_slug(
        self, slug: str, *, include_tag: bool | None = None
    ) -> Coroutine[Any, Any, Market]:
        """Get a market by slug."""
        ...
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        id: list[int] | None = None,
        slug: list[str] | None = None,
        clob_token_ids: list[str] | None = None,
        condition_ids: list[str] | None = None,
        liquidity_num_min: float | None = None,
        liquidity_num_max: float | None = None,
        volume_num_min: float | None = None,
        volume_num_max: float | None = None,
        tag_id: int | None = None,
        related_tags: bool | None = None,
        closed: bool | None = None,
        open: bool | None = None,
        archived: bool | None = None,
    ) -> Coroutine[Any, Any, list[Market]]:
        """List markets with optional filters."""
        ...
    def tags(self, id: str) -> Coroutine[Any, Any, list[Tag]]:
        """Get tags for a market."""
        ...

class GammaMarketsSync:
    """Sync namespace for Gamma market endpoints."""
    def get(self, id: str, *, include_tag: bool | None = None) -> Market:
        """Get a market by ID."""
        ...
    def get_by_slug(self, slug: str, *, include_tag: bool | None = None) -> Market:
        """Get a market by slug."""
        ...
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        id: list[int] | None = None,
        slug: list[str] | None = None,
        clob_token_ids: list[str] | None = None,
        condition_ids: list[str] | None = None,
        liquidity_num_min: float | None = None,
        liquidity_num_max: float | None = None,
        volume_num_min: float | None = None,
        volume_num_max: float | None = None,
        tag_id: int | None = None,
        related_tags: bool | None = None,
        closed: bool | None = None,
        open: bool | None = None,
        archived: bool | None = None,
    ) -> list[Market]:
        """List markets with optional filters."""
        ...
    def tags(self, id: str) -> list[Tag]:
        """Get tags for a market."""
        ...

class GammaEvents:
    """Async namespace for Gamma event endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        id: list[int] | None = None,
        slug: list[str] | None = None,
        tag_id: int | None = None,
        tag_slug: str | None = None,
        active: bool | None = None,
        archived: bool | None = None,
        featured: bool | None = None,
        closed: bool | None = None,
        liquidity_min: float | None = None,
        liquidity_max: float | None = None,
        volume_min: float | None = None,
        volume_max: float | None = None,
    ) -> Coroutine[Any, Any, list[Event]]:
        """List events with optional filters."""
        ...
    def get(
        self,
        id: str,
        *,
        include_chat: bool | None = None,
        include_template: bool | None = None,
    ) -> Coroutine[Any, Any, Event]:
        """Get an event by ID."""
        ...
    def get_by_slug(
        self,
        slug: str,
        *,
        include_chat: bool | None = None,
        include_template: bool | None = None,
    ) -> Coroutine[Any, Any, Event]:
        """Get an event by slug."""
        ...
    def tags(self, id: str) -> Coroutine[Any, Any, list[Tag]]:
        """Get tags for an event."""
        ...
    def tweet_count(self, id: str) -> Coroutine[Any, Any, CountResponse]:
        """Get tweet count for an event."""
        ...
    def comment_count(self, id: str) -> Coroutine[Any, Any, CountResponse]:
        """Get comment count for an event."""
        ...

class GammaEventsSync:
    """Sync namespace for Gamma event endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        id: list[int] | None = None,
        slug: list[str] | None = None,
        tag_id: int | None = None,
        tag_slug: str | None = None,
        active: bool | None = None,
        archived: bool | None = None,
        featured: bool | None = None,
        closed: bool | None = None,
        liquidity_min: float | None = None,
        liquidity_max: float | None = None,
        volume_min: float | None = None,
        volume_max: float | None = None,
    ) -> list[Event]:
        """List events with optional filters."""
        ...
    def get(
        self,
        id: str,
        *,
        include_chat: bool | None = None,
        include_template: bool | None = None,
    ) -> Event:
        """Get an event by ID."""
        ...
    def get_by_slug(
        self,
        slug: str,
        *,
        include_chat: bool | None = None,
        include_template: bool | None = None,
    ) -> Event:
        """Get an event by slug."""
        ...
    def tags(self, id: str) -> list[Tag]:
        """Get tags for an event."""
        ...
    def tweet_count(self, id: str) -> CountResponse:
        """Get tweet count for an event."""
        ...
    def comment_count(self, id: str) -> CountResponse:
        """Get comment count for an event."""
        ...

class GammaSeries:
    """Async namespace for Gamma series endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ascending: bool | None = None,
        closed: bool | None = None,
        slug: list[str] | None = None,
        include_chat: bool | None = None,
        recurrence: str | None = None,
    ) -> Coroutine[Any, Any, list[SeriesData]]:
        """List series with optional filters."""
        ...
    def get(
        self, id: str, *, include_chat: bool | None = None
    ) -> Coroutine[Any, Any, SeriesData]:
        """Get a series by ID."""
        ...

class GammaSeriesSync:
    """Sync namespace for Gamma series endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        ascending: bool | None = None,
        closed: bool | None = None,
        slug: list[str] | None = None,
        include_chat: bool | None = None,
        recurrence: str | None = None,
    ) -> list[SeriesData]:
        """List series with optional filters."""
        ...
    def get(self, id: str, *, include_chat: bool | None = None) -> SeriesData:
        """Get a series by ID."""
        ...

class GammaTags:
    """Async namespace for Gamma tag endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        include_template: bool | None = None,
        is_carousel: bool | None = None,
    ) -> Coroutine[Any, Any, list[Tag]]:
        """List tags with optional filters."""
        ...
    def get(self, id: str) -> Coroutine[Any, Any, Tag]:
        """Get a tag by ID."""
        ...
    def get_by_slug(self, slug: str) -> Coroutine[Any, Any, Tag]:
        """Get a tag by slug."""
        ...
    def get_related(
        self,
        id: str,
        *,
        omit_empty: bool | None = None,
        status: str | None = None,
    ) -> Coroutine[Any, Any, list[Tag]]:
        """Get related tags by ID."""
        ...
    def get_related_by_slug(
        self,
        slug: str,
        *,
        omit_empty: bool | None = None,
        status: str | None = None,
    ) -> Coroutine[Any, Any, list[Tag]]:
        """Get related tags by slug."""
        ...

class GammaTagsSync:
    """Sync namespace for Gamma tag endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        include_template: bool | None = None,
        is_carousel: bool | None = None,
    ) -> list[Tag]:
        """List tags with optional filters."""
        ...
    def get(self, id: str) -> Tag:
        """Get a tag by ID."""
        ...
    def get_by_slug(self, slug: str) -> Tag:
        """Get a tag by slug."""
        ...
    def get_related(
        self,
        id: str,
        *,
        omit_empty: bool | None = None,
        status: str | None = None,
    ) -> list[Tag]:
        """Get related tags by ID."""
        ...
    def get_related_by_slug(
        self,
        slug: str,
        *,
        omit_empty: bool | None = None,
        status: str | None = None,
    ) -> list[Tag]:
        """Get related tags by slug."""
        ...

class GammaComments:
    """Async namespace for Gamma comment endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        parent_entity_type: str | None = None,
        parent_entity_id: int | None = None,
        get_positions: bool | None = None,
        holders_only: bool | None = None,
    ) -> Coroutine[Any, Any, list[Comment]]:
        """List comments with optional filters."""
        ...
    def get(self, id: str) -> Coroutine[Any, Any, Comment]:
        """Get a comment by ID."""
        ...
    def by_user(self, address: str) -> Coroutine[Any, Any, list[Comment]]:
        """Get comments by a user address."""
        ...

class GammaCommentsSync:
    """Sync namespace for Gamma comment endpoints."""
    def list(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        parent_entity_type: str | None = None,
        parent_entity_id: int | None = None,
        get_positions: bool | None = None,
        holders_only: bool | None = None,
    ) -> list[Comment]:
        """List comments with optional filters."""
        ...
    def get(self, id: str) -> Comment:
        """Get a comment by ID."""
        ...
    def by_user(self, address: str) -> list[Comment]:
        """Get comments by a user address."""
        ...

class GammaSports:
    """Async namespace for Gamma sports endpoints."""
    def list(self) -> Coroutine[Any, Any, list[SportMetadata]]:
        """List all sports."""
        ...
    def market_types(self) -> Coroutine[Any, Any, Any]:
        """Get available sport market types."""
        ...
    def list_teams(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        league: list[str] | None = None,
        name: list[str] | None = None,
        abbreviation: list[str] | None = None,
    ) -> Coroutine[Any, Any, list[Team]]:
        """List teams with optional filters."""
        ...

class GammaSportsSync:
    """Sync namespace for Gamma sports endpoints."""
    def list(self) -> list[SportMetadata]:
        """List all sports."""
        ...
    def market_types(self) -> Any:
        """Get available sport market types."""
        ...
    def list_teams(
        self,
        *,
        limit: int | None = None,
        offset: int | None = None,
        order: str | None = None,
        ascending: bool | None = None,
        league: list[str] | None = None,
        name: list[str] | None = None,
        abbreviation: list[str] | None = None,
    ) -> list[Team]:
        """List teams with optional filters."""
        ...

class GammaSearch:
    """Async namespace for Gamma search endpoints."""
    def public_search(
        self,
        query: str,
        *,
        limit_per_type: int | None = None,
        page: int | None = None,
        cache: bool | None = None,
        events_status: str | None = None,
        events_tag: list[int] | None = None,
        keep_closed_markets: int | None = None,
        sort: str | None = None,
        search_tags: bool | None = None,
        search_profiles: bool | None = None,
    ) -> Coroutine[Any, Any, SearchResponse]:
        """Search markets, events, and profiles."""
        ...

class GammaSearchSync:
    """Sync namespace for Gamma search endpoints."""
    def public_search(
        self,
        query: str,
        *,
        limit_per_type: int | None = None,
        page: int | None = None,
        cache: bool | None = None,
        events_status: str | None = None,
        events_tag: list[int] | None = None,
        keep_closed_markets: int | None = None,
        sort: str | None = None,
        search_tags: bool | None = None,
        search_profiles: bool | None = None,
    ) -> SearchResponse:
        """Search markets, events, and profiles."""
        ...

class GammaUser:
    """Async namespace for Gamma user endpoints."""
    def get(self, address: str) -> Coroutine[Any, Any, UserResponse]:
        """Get a user by address."""
        ...

class GammaUserSync:
    """Sync namespace for Gamma user endpoints."""
    def get(self, address: str) -> UserResponse:
        """Get a user by address."""
        ...

class GammaHealth:
    """Async namespace for Gamma health endpoints."""
    def ping(self) -> Coroutine[Any, Any, float]:
        """Ping the Gamma API and return latency in seconds."""
        ...

class GammaHealthSync:
    """Sync namespace for Gamma health endpoints."""
    def ping(self) -> float:
        """Ping the Gamma API and return latency in seconds."""
        ...

# =============================================================================
# CLOB namespace classes
# =============================================================================

class ClobMarkets:
    """Async namespace for CLOB market endpoints."""
    def get(self, condition_id: str) -> Coroutine[Any, Any, ClobMarket]:
        """Get a CLOB market by condition ID."""
        ...
    def get_by_token_ids(
        self, token_ids: list[str]
    ) -> Coroutine[Any, Any, ListMarketsResponse]:
        """Get markets by token IDs."""
        ...
    def list(self) -> Coroutine[Any, Any, ListMarketsResponse]:
        """List all CLOB markets."""
        ...
    def order_book(self, token_id: str) -> Coroutine[Any, Any, OrderBook]:
        """Get the order book for a token."""
        ...
    def price(
        self, token_id: str, side: str
    ) -> Coroutine[Any, Any, PriceResponse]:
        """Get the price for a token and side."""
        ...
    def midpoint(
        self, token_id: str
    ) -> Coroutine[Any, Any, MidpointResponse]:
        """Get the midpoint price for a token."""
        ...
    def prices_history(
        self, token_id: str
    ) -> Coroutine[Any, Any, PricesHistoryResponse]:
        """Get the price history for a token."""
        ...
    def neg_risk(
        self, token_id: str
    ) -> Coroutine[Any, Any, NegRiskResponse]:
        """Check if a token uses negative risk."""
        ...
    def fee_rate(
        self, token_id: str
    ) -> Coroutine[Any, Any, FeeRateResponse]:
        """Get the fee rate for a token."""
        ...
    def tick_size(
        self, token_id: str
    ) -> Coroutine[Any, Any, TickSizeResponse]:
        """Get the minimum tick size for a token."""
        ...
    def spread(
        self, token_id: str
    ) -> Coroutine[Any, Any, SpreadResponse]:
        """Get the bid-ask spread for a token."""
        ...
    def last_trade_price(
        self, token_id: str
    ) -> Coroutine[Any, Any, LastTradePriceResponse]:
        """Get the last trade price for a token."""
        ...
    def live_activity(
        self, condition_id: str
    ) -> Coroutine[Any, Any, list[LiveActivityEvent]]:
        """Get live activity events for a market."""
        ...
    def simplified(self) -> Coroutine[Any, Any, ListMarketsResponse]:
        """List markets in simplified format."""
        ...
    def sampling(self) -> Coroutine[Any, Any, ListMarketsResponse]:
        """List sampling markets."""
        ...
    def sampling_simplified(self) -> Coroutine[Any, Any, ListMarketsResponse]:
        """List sampling markets in simplified format."""
        ...
    def calculate_price(
        self, token_id: str, side: str, amount: str
    ) -> Coroutine[Any, Any, CalculatePriceResponse]:
        """Calculate the price for a given amount."""
        ...

class ClobMarketsSync:
    """Sync namespace for CLOB market endpoints."""
    def get(self, condition_id: str) -> ClobMarket:
        """Get a CLOB market by condition ID."""
        ...
    def get_by_token_ids(self, token_ids: list[str]) -> ListMarketsResponse:
        """Get markets by token IDs."""
        ...
    def list(self) -> ListMarketsResponse:
        """List all CLOB markets."""
        ...
    def order_book(self, token_id: str) -> OrderBook:
        """Get the order book for a token."""
        ...
    def price(self, token_id: str, side: str) -> PriceResponse:
        """Get the price for a token and side."""
        ...
    def midpoint(self, token_id: str) -> MidpointResponse:
        """Get the midpoint price for a token."""
        ...
    def prices_history(self, token_id: str) -> PricesHistoryResponse:
        """Get the price history for a token."""
        ...
    def neg_risk(self, token_id: str) -> NegRiskResponse:
        """Check if a token uses negative risk."""
        ...
    def fee_rate(self, token_id: str) -> FeeRateResponse:
        """Get the fee rate for a token."""
        ...
    def tick_size(self, token_id: str) -> TickSizeResponse:
        """Get the minimum tick size for a token."""
        ...
    def spread(self, token_id: str) -> SpreadResponse:
        """Get the bid-ask spread for a token."""
        ...
    def last_trade_price(self, token_id: str) -> LastTradePriceResponse:
        """Get the last trade price for a token."""
        ...
    def live_activity(self, condition_id: str) -> list[LiveActivityEvent]:
        """Get live activity events for a market."""
        ...
    def simplified(self) -> ListMarketsResponse:
        """List markets in simplified format."""
        ...
    def sampling(self) -> ListMarketsResponse:
        """List sampling markets."""
        ...
    def sampling_simplified(self) -> ListMarketsResponse:
        """List sampling markets in simplified format."""
        ...
    def calculate_price(
        self, token_id: str, side: str, amount: str
    ) -> CalculatePriceResponse:
        """Calculate the price for a given amount."""
        ...

class ClobHealth:
    """Async namespace for CLOB health endpoints."""
    def ping(self) -> Coroutine[Any, Any, float]:
        """Ping the CLOB API and return latency in seconds."""
        ...
    def server_time(self) -> Coroutine[Any, Any, ServerTimeResponse]:
        """Get the server time."""
        ...

class ClobHealthSync:
    """Sync namespace for CLOB health endpoints."""
    def ping(self) -> float:
        """Ping the CLOB API and return latency in seconds."""
        ...
    def server_time(self) -> ServerTimeResponse:
        """Get the server time."""
        ...

# =============================================================================
# Data namespace classes
# =============================================================================

class DataApiTrades:
    """Async namespace for Data API trade endpoints."""
    def list(
        self,
        *,
        user: str | None = None,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        side: str | None = None,
        taker_only: bool | None = None,
        filter_type: str | None = None,
        filter_amount: float | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Coroutine[Any, Any, list[Trade]]:
        """List trades with optional filters."""
        ...

class DataApiTradesSync:
    """Sync namespace for Data API trade endpoints."""
    def list(
        self,
        *,
        user: str | None = None,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        side: str | None = None,
        taker_only: bool | None = None,
        filter_type: str | None = None,
        filter_amount: float | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Trade]:
        """List trades with optional filters."""
        ...

class DataApiHolders:
    """Async namespace for Data API holder endpoints."""
    def list(
        self,
        markets: list[str],
        *,
        limit: int | None = None,
        min_balance: int | None = None,
    ) -> Coroutine[Any, Any, list[MarketHolders]]:
        """List holders for given markets."""
        ...

class DataApiHoldersSync:
    """Sync namespace for Data API holder endpoints."""
    def list(
        self,
        markets: list[str],
        *,
        limit: int | None = None,
        min_balance: int | None = None,
    ) -> list[MarketHolders]:
        """List holders for given markets."""
        ...

class DataApiOpenInterest:
    """Async namespace for Data API open interest endpoints."""
    def get(
        self, *, market: list[str] | None = None
    ) -> Coroutine[Any, Any, list[OpenInterest]]:
        """Get open interest, optionally filtered by market."""
        ...

class DataApiOpenInterestSync:
    """Sync namespace for Data API open interest endpoints."""
    def get(self, *, market: list[str] | None = None) -> list[OpenInterest]:
        """Get open interest, optionally filtered by market."""
        ...

class DataApiLiveVolume:
    """Async namespace for Data API live volume endpoints."""
    def get(self, event_id: int) -> Coroutine[Any, Any, list[LiveVolume]]:
        """Get live volume for an event."""
        ...

class DataApiLiveVolumeSync:
    """Sync namespace for Data API live volume endpoints."""
    def get(self, event_id: int) -> list[LiveVolume]:
        """Get live volume for an event."""
        ...

class DataApiLeaderboard:
    """Async namespace for Data API leaderboard endpoints."""
    def get(
        self,
        *,
        category: str | None = None,
        time_period: str | None = None,
        order_by: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        user: str | None = None,
        user_name: str | None = None,
    ) -> Coroutine[Any, Any, list[TraderRanking]]:
        """Get the trader leaderboard."""
        ...

class DataApiLeaderboardSync:
    """Sync namespace for Data API leaderboard endpoints."""
    def get(
        self,
        *,
        category: str | None = None,
        time_period: str | None = None,
        order_by: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        user: str | None = None,
        user_name: str | None = None,
    ) -> list[TraderRanking]:
        """Get the trader leaderboard."""
        ...

class DataApiBuilders:
    """Async namespace for Data API builder endpoints."""
    def leaderboard(
        self,
        *,
        time_period: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Coroutine[Any, Any, list[BuilderRanking]]:
        """Get the builder leaderboard."""
        ...
    def volume(
        self, *, time_period: str | None = None
    ) -> Coroutine[Any, Any, list[BuilderVolume]]:
        """Get builder volume data."""
        ...

class DataApiBuildersSync:
    """Sync namespace for Data API builder endpoints."""
    def leaderboard(
        self,
        *,
        time_period: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[BuilderRanking]:
        """Get the builder leaderboard."""
        ...
    def volume(
        self, *, time_period: str | None = None
    ) -> list[BuilderVolume]:
        """Get builder volume data."""
        ...

class DataApiHealth:
    """Async namespace for Data API health endpoints."""
    def ping(self) -> Coroutine[Any, Any, float]:
        """Ping the Data API and return latency in seconds."""
        ...

class DataApiHealthSync:
    """Sync namespace for Data API health endpoints."""
    def ping(self) -> float:
        """Ping the Data API and return latency in seconds."""
        ...

class DataApiUser:
    """Async namespace for user-scoped Data API endpoints."""
    def list_positions(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        size_threshold: float | None = None,
        redeemable: bool | None = None,
        mergeable: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
        title: str | None = None,
    ) -> Coroutine[Any, Any, list[Position]]:
        """List open positions for the user."""
        ...
    def positions_value(
        self, *, market: list[str] | None = None
    ) -> Coroutine[Any, Any, list[UserValue]]:
        """Get position values for the user."""
        ...
    def closed_positions(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        title: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
    ) -> Coroutine[Any, Any, list[ClosedPosition]]:
        """List closed positions for the user."""
        ...
    def trades(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        side: str | None = None,
        taker_only: bool | None = None,
        filter_type: str | None = None,
        filter_amount: float | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Coroutine[Any, Any, list[Trade]]:
        """List trades for the user."""
        ...
    def activity(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        activity_type: list[str] | None = None,
        side: str | None = None,
        start: int | None = None,
        end: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
    ) -> Coroutine[Any, Any, list[Activity]]:
        """List activity events for the user."""
        ...
    def traded(self) -> Coroutine[Any, Any, UserTraded]:
        """Check if the user has traded."""
        ...

class DataApiUserSync:
    """Sync namespace for user-scoped Data API endpoints."""
    def list_positions(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        size_threshold: float | None = None,
        redeemable: bool | None = None,
        mergeable: bool | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
        title: str | None = None,
    ) -> list[Position]:
        """List open positions for the user."""
        ...
    def positions_value(
        self, *, market: list[str] | None = None
    ) -> list[UserValue]:
        """Get position values for the user."""
        ...
    def closed_positions(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        title: str | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
    ) -> list[ClosedPosition]:
        """List closed positions for the user."""
        ...
    def trades(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        side: str | None = None,
        taker_only: bool | None = None,
        filter_type: str | None = None,
        filter_amount: float | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> list[Trade]:
        """List trades for the user."""
        ...
    def activity(
        self,
        *,
        market: list[str] | None = None,
        event_id: list[str] | None = None,
        activity_type: list[str] | None = None,
        side: str | None = None,
        start: int | None = None,
        end: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
        sort_by: str | None = None,
        sort_direction: str | None = None,
    ) -> list[Activity]:
        """List activity events for the user."""
        ...
    def traded(self) -> UserTraded:
        """Check if the user has traded."""
        ...

# =============================================================================
# Gamma client classes
# =============================================================================

class Gamma:
    """Async client for the Gamma market data API."""
    def __init__(
        self,
        *,
        base_url: str | None = None,
        timeout_ms: int | None = None,
        pool_size: int | None = None,
    ) -> None: ...
    def markets(self) -> GammaMarkets:
        """Access market endpoints."""
        ...
    def events(self) -> GammaEvents:
        """Access event endpoints."""
        ...
    def series(self) -> GammaSeries:
        """Access series endpoints."""
        ...
    def tags(self) -> GammaTags:
        """Access tag endpoints."""
        ...
    def comments(self) -> GammaComments:
        """Access comment endpoints."""
        ...
    def sports(self) -> GammaSports:
        """Access sports endpoints."""
        ...
    def search(self) -> GammaSearch:
        """Access search endpoints."""
        ...
    def user(self) -> GammaUser:
        """Access user endpoints."""
        ...
    def health(self) -> GammaHealth:
        """Access health endpoints."""
        ...

class GammaSync:
    """Sync client for the Gamma market data API."""
    def __init__(
        self,
        *,
        base_url: str | None = None,
        timeout_ms: int | None = None,
        pool_size: int | None = None,
    ) -> None: ...
    def markets(self) -> GammaMarketsSync:
        """Access market endpoints."""
        ...
    def events(self) -> GammaEventsSync:
        """Access event endpoints."""
        ...
    def series(self) -> GammaSeriesSync:
        """Access series endpoints."""
        ...
    def tags(self) -> GammaTagsSync:
        """Access tag endpoints."""
        ...
    def comments(self) -> GammaCommentsSync:
        """Access comment endpoints."""
        ...
    def sports(self) -> GammaSportsSync:
        """Access sports endpoints."""
        ...
    def search(self) -> GammaSearchSync:
        """Access search endpoints."""
        ...
    def user(self) -> GammaUserSync:
        """Access user endpoints."""
        ...
    def health(self) -> GammaHealthSync:
        """Access health endpoints."""
        ...

# =============================================================================
# CLOB client classes
# =============================================================================

class ClobClient:
    """Async client for the CLOB trading API."""
    def __init__(self) -> None: ...
    def markets(self) -> ClobMarkets:
        """Access market endpoints."""
        ...
    def health(self) -> ClobHealth:
        """Access health endpoints."""
        ...

class ClobClientSync:
    """Sync client for the CLOB trading API."""
    def __init__(self) -> None: ...
    def markets(self) -> ClobMarketsSync:
        """Access market endpoints."""
        ...
    def health(self) -> ClobHealthSync:
        """Access health endpoints."""
        ...

# =============================================================================
# Data client classes
# =============================================================================

class DataApi:
    """Async client for the Polymarket data API."""
    def __init__(
        self,
        *,
        base_url: str | None = None,
        timeout_ms: int | None = None,
        pool_size: int | None = None,
    ) -> None: ...
    def user(self, address: str) -> DataApiUser:
        """Access user-scoped endpoints for a given address."""
        ...
    def trades(self) -> DataApiTrades:
        """Access trade endpoints."""
        ...
    def holders(self) -> DataApiHolders:
        """Access holder endpoints."""
        ...
    def open_interest(self) -> DataApiOpenInterest:
        """Access open interest endpoints."""
        ...
    def live_volume(self) -> DataApiLiveVolume:
        """Access live volume endpoints."""
        ...
    def leaderboard(self) -> DataApiLeaderboard:
        """Access leaderboard endpoints."""
        ...
    def builders(self) -> DataApiBuilders:
        """Access builder endpoints."""
        ...
    def health(self) -> DataApiHealth:
        """Access health endpoints."""
        ...

class DataApiSync:
    """Sync client for the Polymarket data API."""
    def __init__(
        self,
        *,
        base_url: str | None = None,
        timeout_ms: int | None = None,
        pool_size: int | None = None,
    ) -> None: ...
    def user(self, address: str) -> DataApiUserSync:
        """Access user-scoped endpoints for a given address."""
        ...
    def trades(self) -> DataApiTradesSync:
        """Access trade endpoints."""
        ...
    def holders(self) -> DataApiHoldersSync:
        """Access holder endpoints."""
        ...
    def open_interest(self) -> DataApiOpenInterestSync:
        """Access open interest endpoints."""
        ...
    def live_volume(self) -> DataApiLiveVolumeSync:
        """Access live volume endpoints."""
        ...
    def leaderboard(self) -> DataApiLeaderboardSync:
        """Access leaderboard endpoints."""
        ...
    def builders(self) -> DataApiBuildersSync:
        """Access builder endpoints."""
        ...
    def health(self) -> DataApiHealthSync:
        """Access health endpoints."""
        ...
