#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["polymarket-client==0.11.0"]
#
# [tool.uv]
# exclude-newer = "2026-09-25T00:00:00Z"
# ///
"""Generate ERC-7739 / session-key golden vectors from Polymarket's official py-sdk.

polyoxide pins its Deposit Wallet (signature type 3) signing against these bytes.
The fixture order is py-sdk's own golden fixture (tests/unit/test_order_typed_data_golden.py),
signed with Anvil key #0; the session signer is Anvil address #1.

This script imports py-sdk's private modules (`polymarket._internal...`), which are not a
stable public API, so it is expected to need import-path fixes after a py-sdk upgrade.

Usage:
    uv run scripts/capture_session_key_vectors.py polyoxide-clob/tests/fixtures/session_keys

Writes `order_vectors.json` and `PROVENANCE.md`. Re-run after a py-sdk upgrade; review the
diff before committing.
"""
import importlib.metadata
import json
import re
import sys
import tomllib
from pathlib import Path

from eth_account import Account
from eth_account.messages import encode_typed_data
from eth_utils.crypto import keccak
from polymarket._internal.actions.orders.typed_data import (
    _app_domain_separator,
    _order_contents_hash,
    build_order_signature,
    build_order_typed_data,
)
from polymarket._internal.actions.orders.types import BYTES32_ZERO, UnsignedOrder
from polymarket._internal.wallet import wrap_deposit_wallet_session_signer_signature
from polymarket.models.types import TokenId
from polymarket.types import EvmAddress, HexString

ANVIL_KEY_0 = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
ANVIL_ADDR_1 = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
DEPOSIT_WALLET = EvmAddress("0x57ffbc34de23124faeb8387fcd689d314e57accd")
EXCHANGES = {
    # py-sdk's golden fixture uses the V1 exchange address; keep it so the digest
    # cross-checks against their pinned value.
    "v1_exchange": "0x4bfb41d5b3570defd03c39a9a4d8de6bd8b8982e",
    # polyoxide's Polygon mainnet CTF Exchange V2, what the client signs against.
    "v2_exchange": "0xE111180000d2663C0091e4f400237545B87B996B",
}

# py-sdk's own pinned digest for this exact order, from its
# tests/unit/test_order_typed_data_golden.py. If this stops matching, either py-sdk's
# signing bytes changed upstream or our fixture no longer mirrors theirs — investigate
# before trusting anything else this script produces.
PY_SDK_GOLDEN_DIGEST = "0x1b9566eedd9589a73275df23a3a9d9e2e9897e76d31cd46d436f1b824d161b33"


def fixture(exchange: str) -> UnsignedOrder:
    return UnsignedOrder(
        builder=BYTES32_ZERO,
        chain_id=137,
        exchange_address=EvmAddress(exchange),
        expiration=0,
        maker=DEPOSIT_WALLET,
        maker_amount=1_000_000,
        metadata=BYTES32_ZERO,
        order_type="GTC",
        salt=1,
        side="BUY",
        signature_type=3,
        signer=DEPOSIT_WALLET,
        taker_amount=500_000,
        timestamp=0,
        token_id=TokenId("1"),
    )


def digest(typed_data: dict) -> str:
    signable = encode_typed_data(full_message=typed_data)
    return "0x" + keccak(b"\x19\x01" + signable.header + signable.body).hex()


# The canonical PEP 723 block-extraction regex, straight from the spec.
_PEP_723_BLOCK_RE = re.compile(
    r"(?m)^# /// (?P<type>[a-zA-Z0-9-]+)$\s(?P<content>(^#(| .*)$\s)+)^# ///$"
)


def read_dependency_cutoff() -> str:
    """Read `[tool.uv].exclude-newer` from this file's own PEP 723 metadata block.

    Keeps PROVENANCE.md's stated cutoff in sync with the pin that actually governs
    dependency resolution, instead of duplicating the date as a second literal.
    """
    match = _PEP_723_BLOCK_RE.search(Path(__file__).read_text())
    content = "".join(
        line[2:] if line.startswith("# ") else line[1:]
        for line in match.group("content").splitlines(keepends=True)
    )
    metadata = tomllib.loads(content)
    return metadata["tool"]["uv"]["exclude-newer"]


def order_provenance(order: UnsignedOrder) -> dict:
    return {
        "chain_id": order.chain_id,
        "salt": order.salt,
        "token_id": str(order.token_id),
        "maker_amount": order.maker_amount,
        "taker_amount": order.taker_amount,
        "side": order.side,
        "signature_type": order.signature_type,
        "timestamp": order.timestamp,
        "expiration": order.expiration,
        "metadata": order.metadata,
        "builder": order.builder,
    }


def write_provenance(out_dir: Path, sdk_version: str, dependency_cutoff: str) -> None:
    text = f"""# Deposit Wallet (session-key) order-signing vectors

Generated by `scripts/capture_session_key_vectors.py` (run:
`uv run scripts/capture_session_key_vectors.py polyoxide-clob/tests/fixtures/session_keys`)
against Polymarket's official Python SDK, `polymarket-client=={sdk_version}` — not a live
host. Dependency resolution is pinned to `exclude-newer = {dependency_cutoff}` (the
script's own PEP 723 metadata), so a rerun reproduces byte-identical output regardless of
the date it is run, until that cutoff or the pinned `polymarket-client` version changes.

The order is py-sdk's own golden fixture (`tests/unit/test_order_typed_data_golden.py`),
signed with Anvil key #0. Generation asserts the `v1_exchange` vector's `envelope_digest`
against py-sdk's pinned value before writing anything, so this fixture cannot drift from
theirs silently.

`session_signature` is a byte-pinning vector only, not a signature a real session key
would produce: the session-signer envelope names Anvil address #1 as the session signer,
but Anvil key #0 produced the inner order signature. The two identities are deliberately
mismatched so the fixture can pin bytes without coordinating two live signers.

| Fixture | Command |
|---|---|
| `order_vectors.json` | `uv run scripts/capture_session_key_vectors.py polyoxide-clob/tests/fixtures/session_keys` |
"""
    (out_dir / "PROVENANCE.md").write_text(text)


def main(out_dir: Path) -> None:
    signer = Account.from_key(ANVIL_KEY_0)
    sdk_version = importlib.metadata.version("polymarket-client")
    dependency_cutoff = read_dependency_cutoff()
    out = {}
    for name, exchange in EXCHANGES.items():
        order = fixture(exchange)
        typed_data = build_order_typed_data(order)
        inner = "0x" + signer.sign_typed_data(full_message=typed_data).signature.hex()
        wrapped = build_order_signature(order, HexString(inner))
        session = wrap_deposit_wallet_session_signer_signature(
            EvmAddress(ANVIL_ADDR_1), wrapped
        )
        envelope_digest = digest(typed_data)
        if name == "v1_exchange" and envelope_digest != PY_SDK_GOLDEN_DIGEST:
            print(
                "envelope_digest for v1_exchange does not match py-sdk's golden "
                f"fixture:\n  got:      {envelope_digest}\n"
                f"  expected: {PY_SDK_GOLDEN_DIGEST}",
                file=sys.stderr,
            )
            sys.exit(1)
        out[name] = {
            "exchange": exchange,
            "deposit_wallet": DEPOSIT_WALLET,
            "signer_address": signer.address,
            "session_signer": ANVIL_ADDR_1,
            "envelope_digest": envelope_digest,
            "app_domain_separator": _app_domain_separator(
                order, protocol_version=order.protocol_version
            ),
            "contents_hash": "0x" + _order_contents_hash(order).hex(),
            "inner_signature": inner,
            "wrapped_signature": wrapped,
            "session_signature": session,
            "order": order_provenance(order),
        }
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "order_vectors.json").write_text(json.dumps(out, indent=2) + "\n")
    write_provenance(out_dir, sdk_version, dependency_cutoff)
    print(f"wrote {out_dir / 'order_vectors.json'}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(Path(sys.argv[1]))
